-- 0045: every privilege the API roles hold, written down.
--
-- No migration before this one granted a table to anon, authenticated or
-- service_role. None had to: the hosted project was created while Supabase's
-- default privileges handed every new table and function straight to all three
-- roles, and RLS did the gating. Current Supabase stacks no longer do that for
-- objects `postgres` creates, so a database built from these migrations today
-- -- the local stack, a restore, a fresh project -- came up with service_role
-- unable to insert into `orgs`. Every integration suite failed in setup, and
-- the demo route could not call record_demo() at all.
--
-- Three parts.
--
-- 1. What the hosted project already has, stated. Generated by diffing the
--    effective privileges of the three roles on the hosted project against a
--    fresh build of 0001-0044. Every statement in this part is one the hosted
--    project already satisfies, so there it changes nothing; everywhere else
--    it produces the same database.
--
-- 2. Three things the old defaults handed out that nobody meant to. A
--    `revoke ... from public` does not undo a DIRECT grant, and the old
--    default granted directly, so 0021's revoke on record_demo() never took
--    effect: anon could execute it, which is anyone holding the publishable
--    key, and that key ships in the browser bundle. record_demo() is SECURITY
--    DEFINER and writes the demo columns past the guard.
--
-- 3. The hosted project's default privileges brought in line with a fresh
--    stack's: a new table or function is reachable by no API role until its
--    own migration grants it. That is what stops (2) from happening again, and
--    it means a migration that forgets a grant fails the local suite instead
--    of working in one environment and not the other.

-- ---------------------------------------------------------------------------
-- 1. Parity with the hosted project
-- ---------------------------------------------------------------------------
-- anon holds table privileges here because it does on the hosted project. No
-- policy names anon, so RLS denies it every row; mirroring that exactly is what
-- lets the "anon reads nothing" tests prove RLS rather than a missing grant.

grant select, insert, update, delete on table
  public.alerts,
  public.dedupe_reviews,
  public.import_rows,
  public.imports,
  public.lead_evidence,
  public.leads,
  public.mailbox_events,
  public.mailboxes,
  public.org_members,
  public.org_settings,
  public.orgs,
  public.scheduled_sends,
  public.suppressions,
  public.templates
  to anon, authenticated, service_role;

-- 0005 gives members no UPDATE or DELETE on the event log: it is append-only
-- for anybody with a session.
grant select, insert, update, delete on table public.lead_events to anon, service_role;
grant select, insert on table public.lead_events to authenticated;

-- Refresh tokens. No other role, ever.
grant select, insert, update, delete on table public.mailbox_secrets to service_role;

-- Every member-facing RPC already grants authenticated in its own migration.
-- These are the service-role halves the old default supplied silently, plus
-- record_demo(), which the demo ingest route calls and nothing else may.
grant execute on function
  public.assign_lead_owners(jsonb, boolean),
  public.backfill_lead_owners(text, boolean),
  public.backfill_sheet_touch_history(text, boolean, boolean, boolean),
  public.background_jobs_status(),
  public.cancel_scheduled_send(uuid, text),
  public.claim_lead(uuid),
  public.claim_leads_from_pool(integer),
  public.close_lead(uuid, public.terminal_outcome, text),
  public.dashboard_activity(integer),
  public.queue_composed_send(uuid, text, text, timestamptz, timestamp, uuid, smallint, uuid),
  public.queue_lead_without_audit(uuid),
  public.reassign_lead(uuid, uuid),
  public.record_demo(uuid, text, text, text, jsonb),
  public.release_lead(uuid),
  public.remove_demo_leads(boolean),
  public.repair_lead_websites(boolean),
  public.repair_stalled_sends(boolean),
  public.reroute_planned_sends_to_owner(boolean),
  public.resolve_stalled_send(uuid, boolean),
  public.revise_composed_send(uuid, text, text),
  public.set_lead_stage(uuid, public.pipeline_stage, text)
  to service_role;

-- ---------------------------------------------------------------------------
-- 2. What nobody meant to hand out
-- ---------------------------------------------------------------------------

-- The demo ingest route runs as the service role. No session should ever be
-- able to mark a lead demo-ready, and no anonymous caller should be able to do
-- anything at all.
revoke execute on function public.record_demo(uuid, text, text, text, jsonb)
  from public, anon, authenticated;

-- /settings reads this as a member. A visitor with no session has no business
-- knowing what the scheduler runs, or when.
revoke execute on function public.background_jobs_status() from public, anon;

-- Called by pg_cron, which runs as postgres, and by a person in the SQL editor.
-- The `app` schema is not exposed over the API, so this was never reachable
-- from outside; it is still not a thing any API role should hold.
revoke execute on function
  app.call_job(text),
  app.enable_background_jobs(),
  app.disable_background_jobs()
  from public, anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 3. Nothing new is reachable until its migration says so
-- ---------------------------------------------------------------------------
-- On a fresh stack these are already the defaults and this changes nothing. On
-- the hosted project it stops the next table or function from being handed to
-- every API role the moment it is created.

alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated, service_role;

alter default privileges for role postgres in schema public
  revoke execute on functions from public, anon, authenticated, service_role;
